### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mre** [analysis-dev/diktat#1088]
## Describe the bug

The website at https://www.cqfn.org/diKTat is currently not reachable.
See https://github.com/analysis-tools-dev/static-analysis/issues/879.

**Comment by akuleshov7** [comment]
Thank you for your report! Yes, we migrated to this brand new repo and now are establishing all related automation :)

**Comment by akuleshov7** [comment]
Moved to analysis-dev.github.io/diktat/
