### ISSUE TITLE
`COMPLEX_EXPRESSION` can be softened for gradle scripts

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/diktat#1148]
## Describe the bug
```kotlin
dependencies {
    api(projects.saveCloudCommon)
    implementation(libs.spring.cloud.starter.gateway)
}
```
causes a lot of `COMPLEX_EXPRESSIONS`, but it doesn't make sense in gradle configs.

## Environment information
* diktat version: 1.0.0

**Comment by akuleshov7** [comment]
Can be done only for scripts. Need to add the documentation about that also.
