### ISSUE TITLE
Diktat crashes when lambda expression only contains a comment.

### ISSUE THREAD

**Issue by JamesBundgard** [analysis-dev/diktat#1169]
## Describe the bug

Diktat does not correctly handle lambda expressions that only contain a comment.

## Expected behavior

This code:
```
var list = listOf("a", "b", "c")
list.forEach { /* test */ }
```
should result in the following error:
```
[EMPTY_BLOCK_STRUCTURE_ERROR] incorrect format of empty block: empty blocks are forbidden unless it is function with override keyword (cannot be auto-corrected)
```

## Observed behavior

Gradle gives the following error:
```
java.lang.Error: Internal error in diktat application
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.lang.Object java.lang.Throwable.backtrace accessible: module java.base does not "opens java.lang" to unnamed module @647c3190
```

## Steps to Reproduce

1. Create a new Kotlin project
2. Add the following code:
```
fun main() {
    var list = listOf("a", "b", "c")
    list.forEach { /* test */ }
}
```
3. Run diktat

## Environment information
* diktat version: 0.43.0 (gradle plugin version 1.0.1)
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): Command line "./gradlew diktatCheck"
* kotlin version: 1.6.10
* operating system: macOS Monterey version 12.1
* link to a project (if your project is public):

**Comment by petertrr** [comment]
Hi, thanks for your report! The issue you are facing is caused not by diktat, but by Java. You can check on https://ktlint-demo.herokuapp.com that diktat correctly checks the code you have provided.

Which JVM version are you using? I think there are some problems with running kotlin-compiler-embeddable (which is used by diktat under the hood) on newer JVMs (16 or 17) on Macs (see #1165 for example).

**Comment by JamesBundgard** [comment]
That makes sense. I'm using OpenJDK 17 on the new M1 MacBook.

**Comment by akuleshov7** [comment]
@JamesBundgard I had mostly the same issue, but it looks that we need to wait for some updates from JB

**Comment by akuleshov7** [comment]
Actually that is my first MAC in the life and I was very disappointed by the lack of M1-supported libraries :(
Even running docker was a problem :(

@JamesBundgard

**Comment by JamesBundgard** [comment]
@akuleshov7  I've also had a lot of issues getting docker running
