### ISSUE TITLE
gradle diktatFix task cause internal error

### ISSUE THREAD

**Issue by yewton** [analysis-dev/diktat#1203]
## Describe the bug

`diktatFix` task cause following error:

```
[ERROR] 2022-01-31 23:14:36 Internal error has occurred in rule [kdoc-methods]. Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
                       As a workaround you can disable these inspections in yml config: <[KDOC_TRIVIAL_KDOC_ON_FUNCTION, KDOC_WITHOUT_PARAM_TAG, KDOC_WITHOUT_RETURN_TAG, KDOC_WITHOUT_THROWS_TAG, MISSING_KDOC_ON_FUNCTION]>.
                       Root cause of the problem is in [/home/yewton/Projects/testmmdiktat/app/src/main/kotlin/net/yewton/testmmdiktat/app/MessageUtils.kt] file.
java.lang.ExceptionInInitializerError: null
```

```
[ERROR] 2022-01-31 23:14:36 Internal error has occurred in rule [file-structure]. Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
                       As a workaround you can disable these inspections in yml config: <[FILE_CONTAINS_ONLY_COMMENTS, FILE_INCORRECT_BLOCKS_ORDER, FILE_NO_BLANK_LINE_BETWEEN_BLOCKS, FILE_UNORDERED_IMPORTS, FILE_WILDCARD_IMPORTS, UNUSED_IMPORT]>.
                       Root cause of the problem is in [/home/yewton/Projects/testmmdiktat/app/src/test/kotlin/net/yewton/testmmdiktat/app/MessageUtilsTest.kt] file.
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ThrowableInterner
```

## Expected behavior

It fixes without error

## Observed behavior

Described error occurs

## Steps to Reproduce

Checkout https://github.com/yewton/testmmdiktat and run `./gradlew diktatFix`

This project is generated by `gradle init` -> type: application -> lang: Kotlin -> multiple projects: yes

## Environment information
* diktat version:1.0.2
* build tool (maven/gradle):gralde
* how is diktat run (CLI, plugin, etc.):CLI
* kotlin version: ~1.5.31~ *1.6.10*
* operating system:Xubuntu Jammy Jellyfish (development branch) x86_64
* link to a project (if your project is public): https://github.com/yewton/testmmdiktat

**Comment by akuleshov7** [comment]
I check it with the following env:
```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing
```

```
/mnt/d/testmmdiktat/app/src/main/kotlin/net/yewton/testmmdiktat/app/App.kt:1:1: [HEADER_MISSING_IN_NON_SINGLE_CLASS_FILE] files that contain multiple or no classes should contain description of what is inside of this file: there are 0 declared classes and/or objects (cannot be auto-corrected)

/mnt/d/testmmdiktat/app/src/main/kotlin/net/yewton/testmmdiktat/app/MessageUtils.kt:8:24: [KDOC_NO_EMPTY_TAGS] no empty descriptions in tag blocks are allowed: @return (cannot be auto-corrected)
```

**Comment by yewton** [comment]
Thank you for taking your time.

I'm using Temurin Java 17.0.1, and Kitlin 1.6.10 ( I'm sorry I said 1.5.31 at first ).

I added a GitHub Actions to reproduce this: https://github.com/yewton/testmmdiktat/blob/main/.github/workflows/ci.yml

**Comment by petertrr** [comment]
The error `java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ThrowableInterner` is the same as in #1182 and it's about the way JPMS is handled in newer JVMs (starting with 16 AFAIU). @yewton please try the workaround suggested in https://github.com/analysis-dev/diktat/issues/1182#issuecomment-1023099713 with declaring explicitly opened module.

**Comment by yewton** [comment]
It works, thank you!
