### ISSUE TITLE
gradle-plugin: problems with the new `githubActions` mode

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/diktat#1213]
## Expected behavior
SARIF report can be identified by `.sarif` extension

## Observed behavior
https://github.com/analysis-dev/diktat/commit/0698727bcf762ce7a765098dcf36be5cebcca6a1#diff-52618882223ec0dcf8f8568e2158fd7d1f83502da075d9658d3b5e24d92f7d0fR162
SARIF report has the same name, as the project. It makes it really hard to automatically discover these reports.

## Environment information
* diktat version: 1.0.3
* build tool (maven/gradle): gradle

**Comment by petertrr** [comment]
Also, shouldn't https://github.com/analysis-dev/diktat/commit/0698727bcf762ce7a765098dcf36be5cebcca6a1#diff-52618882223ec0dcf8f8568e2158fd7d1f83502da075d9658d3b5e24d92f7d0fR186 contain `rootProject.projectDir` for `user.home`? Now it's not working as expected: https://github.com/analysis-dev/save-cloud/pull/566/checks?check_run_id=5181006513 has incorrect path to a file: `work/save-cloud/save-cloud/save-frontend/src/main/kotlin/org/cqfn/save/frontend/utils/JsUtils.kt`

**Comment by petertrr** [comment]
I've been able to workaround these issues in https://github.com/analysis-dev/save-cloud/pull/566. I suppose the same things should be changed in diktat-gradle-plugin itself to make its usage easier.

**Comment by akuleshov7** [comment]
@petertrr could you please have a look at this with a priority? Let's take it to 1.0.4
