### ISSUE TITLE
Diktat fix and check should be run on the huge Kotlin projects

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/diktat#383]
It is very critical for us now to test diKTat properly

**Comment by petertrr** [comment]
That sounds like a really useful idea, but what exactly do you have in mind? That we should set up a new CI workflow that would checkout other projects and run diktat and we than will analyze build logs?

I think for now we can focus on smaller tasks to make diktat usable: #204 for easier adoption in existing projects, we also should make diktat check of our own code green (~2.5k errors left, a lot of fixes of false-positives on the way), we also can use diktat in diktat-demo and git-stat.

**Comment by petertrr** [comment]
I actually tried to use diktat on git-stat: https://github.com/akuleshov7/git-stat/pull/9.

**Comment by akuleshov7** [comment]
agree, diktat should be fixed first. Let's start from it. Diktat should be consistent with it's own codestyle

**Comment by petertrr** [comment]
We have a [wiki page](https://github.com/cqfn/diKTat/wiki/Projects-we-have-run-diktat-on) to describe results of such attempts.

**Comment by petertrr** [comment]
As @kgevorkyan suggested, it may be time to remember this issue and try to create a CI pipeline, which will be executed (manually) before release

**Comment by akuleshov7** [comment]
We are integrated into different projects already and have a bunch of tests, I think we can close this one
