### ISSUE TITLE
Add enable/disable configuration for debug logging in diktat and ktlint

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/diktat#76]
Now it is awful:
```
if (debug) {
}
```

**Comment by petertrr** [comment]
Other things to consider regarding logging:
* migrate from slf4j to kotlin-logging
* do something not to exclude slf4j-log4j12 from diktat-rules when used as a plugin (use log4j only in our own tests and in fat jar)

**Comment by petertrr** [comment]
Another point regarding logging: both maven and gradle provide slf4j-compatible logger implementation at runtime, so diktat-rules should only include `slf4j-api` in jar and use provided logging implementation.

**Comment by petertrr** [comment]
ktlint 0.44 finally changed logging mechanism to slf4j, so I suppose this issue can be closed. But before closing, we should check if `debug` parameter is needed anymore and also if we have any transitive dependencies on logging implementation in plugins (like https://github.com/analysis-dev/diktat/issues/1269#issuecomment-1098778524)

**Comment by akuleshov7** [comment]
Then we should remove all “legacy debug” logging in diktat? @petertrr

**Comment by petertrr** [comment]
> Then we should remove all “legacy debug” logging in diktat? @petertrr

IIRC, we don't use old ktlint's debug, we always use slf4j loggers, but we'll need to recheck this
