### ISSUE TITLE
Support baseline functionality from newer ktlint versions

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/diktat#800]
In ktlint 0.40 baseline functionality has been introduced. We should support `--baseline` option in plugins and also maybe add maven goal / gradle task for baseline generation.

**Comment by akuleshov7** [comment]
Need to keep in mind that it is possible that we won't be using ktlint and will move to a custom framework... 
https://github.com/analysis-dev/diktat/issues/734

**Comment by petertrr** [comment]
This issue is actually a duplicate of #1129, and the described functionality has been added in #1194
